on:
  push:
    branches:    
      - master
    paths:
      - 'doc/**'
  pull_request:
    branches:    
      - master
    paths:
      - 'doc/**'
name: Copy Md
jobs:
  jobAll:
    name: Copy Documents
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: zh_cn
      uses: andstor/copycat-action@v2.0.0
      with:
        personal_token: ${{ secrets.www }}
        src_path: doc/zh_cn/.
        dst_path: /doc/_posts/zh_cn/mframe
        dst_owner: momentum-design
        dst_repo_name: blog
        clean: true
        username: yulhuang
        email: yulhuang@cisco.com
    - name: en_us
      uses: andstor/copycat-action@v2.0.0
      with:
        personal_token: ${{ secrets.www }}
        src_path: doc/en_us/.
        dst_path: /doc/_posts/en_us/mframe
        dst_owner: momentum-design
        dst_repo_name: blog
        clean: true
        username: yulhuang
        email: yulhuang@cisco.com